### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [williamyaoh/kaiseki#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Looks like this is blocked by https://github.com/docopt/docopt.rs/issues/128. I will follow up in this issue when they have a new release ready.

**Comment by williamyaoh** [comment]
Sounds good, thanks for the heads up.

Yeah, I'm not using rustc-serialize except to work with docopt, so I'd be happy to drop it once
docopt no longer requires it.

**Comment by williamyaoh** [comment]
Closed. I've moved over to `structopt`.
